### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by Martyn0324** [d0p3t/SerpentTiamatXGameAgentPlugin#1]
Hello! I've been using this code as an example for my Game Agent Plugin and I thought you would be able to help me with this problem.

Here's the Traceback error:
```
Traceback (most recent call last):
  File "c:\anaconda\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\serpent\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\Serpent\Scripts\serpent.exe\__main__.py", line 7, in <module>
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\serpent.py", line 52, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\serpent.py", line 369, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\game.py", line 201, in play
    raise e
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\game.py", line 192, in play
    game_agent.on_game_frame(game_frame, frame_handler=frame_handler, **kwargs)
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\game_agent.py", line 115, in on_game_frame
    frame_handler(game_frame, **kwargs)
  File "C:\Users\Administrator\SerpentAI\plugins\SerpentTenshi3GameAgentPlugin\files\serpent_Tenshi3_game_agent.py", line 128, in handle_play
    power = self._measure_power(game_frame)
  File "C:\Users\Administrator\SerpentAI\plugins\SerpentTenshi3GameAgentPlugin\files\serpent_Tenshi3_game_agent.py", line 194, in _measure_power
    score = serpent.ocr.perform_ocr(image=score_grayscale, scale=10, order=5, horizontal_closing=10, vertical_closing=5)
  File "c:\anaconda\envs\serpent\lib\site-packages\serpent\ocr.py", line 110, in perform_ocr
    order=order
  File "c:\anaconda\envs\serpent\lib\site-packages\skimage\transform\_warps.py", line 165, in resize
    tform.estimate(src_corners, dst_corners)
  File "c:\anaconda\envs\serpent\lib\site-packages\skimage\transform\_geometric.py", line 679, in estimate
    _, _, V = np.linalg.svd(A)
  File "<__array_function__ internals>", line 6, in svd
  File "c:\anaconda\envs\serpent\lib\site-packages\numpy\linalg\linalg.py", line 1661, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "c:\anaconda\envs\serpent\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

I suppose the problem lies within scikit-image conversion to RGB. Anyway, here's the function that caused this problem:

```
    def _measure_power(self, game_frame):
        power_area_frame = serpent.cv.extract_region_from_image(game_frame.frame, self.game.screen_regions["Power"])
            
        power_grayscale = np.array(skimage.color.rgb2gray(power_area_frame) * 255, dtype="uint8")
            
        power = serpent.ocr.perform_ocr(image=power_grayscale, scale=10, order=5, horizontal_closing=10, vertical_closing=5)
            
        self.game_state['current_run_power'] = power

        return power
```

I'm using scikit-image==0.14.2

**Comment by Martyn0324** [comment]
Nevermind. I found out that pywin32, used by SerpentAI, wasn't getting the window size of my game correctly. Therefore, my region_mapping wasn't correct.
